version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
